name:                pullpush
version:             0.1.0.0
github:              "oquechy/pullpush"
license:             BSD-3-Clause
author:              "Lisa Vasilenko"
maintainer:          "elizaveta.vasilenko@imdea.org"
copyright:           "2023 Lisa Vasilenko"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/oquechy/pullpush#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  language: Haskell2010
  ghc-options: -fplugin=LiquidHaskell
  dependencies:
  - liquidhaskell
  - liquid-prelude
  